version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - daniel-jonathan

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    assignees:
      - daniel-jonathan